name: Linux
on:
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: "linux-build"
  cancel-in-progress: true
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y xorg-dev libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libvulkan-dev

      - name: Init submodules
        run: |
          git submodule update --init --depth 1 vendor/dawn
          git submodule update --init --recursive vendor/spdlog vendor/imgui vendor/assimp vendor/flecs vendor/tracy vendor/stb vendor/ImGuizmo vendor/JoltPhysics vendor/ozz-animation

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Configure
        run: cmake --preset linux-release

      - name: Build
        run: cmake --build build/linux-release -j2

      - name: Copy files
        run: |
          cp -r Resources bin/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReEngine-Linux
          path: build/linux-release/bin/
          retention-days: 30
