name: MacOS

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "macos-build"
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: macos-26-intel
    steps:
      - uses: actions/checkout@v6

      - name: Init submodules
        run: |
          git submodule update --init --depth 1 vendor/dawn
          git submodule update --init --recursive vendor/spdlog vendor/imgui vendor/assimp vendor/flecs vendor/tracy vendor/stb vendor/ImGuizmo vendor/JoltPhysics vendor/ozz-animation

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Configure
        run: >
          cmake --preset osx-release
          -DCMAKE_CXX_FLAGS_RELEASE="-O2 -DNDEBUG -flto=thin"
          -DCMAKE_C_FLAGS_RELEASE="-O2 -DNDEBUG -flto=thin"
          -DCMAKE_EXE_LINKER_FLAGS_RELEASE="-flto=thin"

      - name: Build
        run: cmake --build build/osx-release -j3

      - name: Copy files
        run: |
          cp -r Resources bin/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ReEngine-macOS
          path: build/osx-release/bin/
          retention-days: 30
